#!/bin/sh
set -eu
dir="$(cd "$(dirname "$0")"; pwd)"
JAVA=java
if [ -n "${JAVA_HOME:-}" ]; then
  JAVA="$JAVA_HOME/bin/java"
fi
exec "$JAVA" -cp "${dir}/sslr-plsql-toolkit-3.8.0.4948.jar:${dir}/out/production/sslr" sslr.Main "$@"
